### PR TITLE
Increase verbosity of server load screen

### LINKED ISSUE #37: Server connection screen isn't verbose enough
The screen displayed while connecting to a server just says `Downloading terrain` even before it's technically downloading terrain. This makes it confusing to figure out why server connection isn't working when it breaks.

- [ ] Add more connection phases and display messages for them
- [ ] Check that the new messages are helpful by direct connecting to a minecraft server that doesn't exist (e.g. `play.stackotter.dev:12345`. At the moment it just says `Downloading terrain` and after solving this problem it should be pretty obvious that connecting to the server has failed.

## Extra information

The way updates are sent from the networking thread (in `DeltaCore`) to the UI (in `DeltaClient`) is through the event bus. To add an event create a struct that conforms to `Event`. See [the existing events](https://github.com/stackotter/delta-client/tree/main/Sources/DeltaCore/Event/Events) as reference. Then in the networking or wherever required, you can use `eventBus.dispatch(YourNewEvent(...))` to notify listeners of the event. Then add handling code for the event to [`PlayServerView.handleClientEvent`](https://github.com/stackotter/delta-client/blob/fdb719d094e5cadf8334e2a3afac088e9c647dc3/Sources/DeltaClient/Views/Play/PlayServerView.swift#L61).

### PR DESCRIPTION
**Pull request by thegail**
# Description

Increase the verbosity of the server load screen. Instead of just saying "Downloading Terrain.." the screen now says "Establishing Connection..." then "Logging In...", then finally "Downloading Chunks..." with an approximate progress indicator. When a connection fails, it also displays a modal error. A minor issue was fixed preventing the client from building on some devices.

Resolves #37

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation comments
- [x] My changes generate no new warnings

### CODE REVIEW

File: Sources/Core/Sources/PluginAPI/Event/World/JoinWorldEvent.swift [hunk 1]
```diff
@@ -2,8 +2,10 @@ import Foundation
 
 public struct JoinWorldEvent: Event {
   public var world: World
+  public var viewDistance: Int
```
Comment (stackotter) [inline Sources/Core/Sources/PluginAPI/Event/World/JoinWorldEvent.swift:5]: use Game.maxViewDistance instead

**Review by stackotter — CHANGES_REQUESTED** [review]
Overall these changes look great! Just that one thing to fix up, then I'll merge it :)

**Review by stackotter — APPROVED** [review]
