### PR TITLE
Make RenderCoordinator errors recoverable

### LINKED ISSUE #175: Make renderer errors recoverable instead of fatal (to help with troubleshooting)
At the moment the client just crashes for most renderer errors (which can happen if caches are outdated). This means that we can't show a nice error message to the user suggesting troubleshooting steps. Instead of fatally crashing, the client should propagate errors back up to the UI.

### PR DESCRIPTION
**Pull request by notdap**
# Description

This pull request ensures that any errors that may surge in RenderCoordinator#init are propagated back to the UI and so that an error message is shown instead of crashing the entire client.

Fixes #175 (not sure if fully)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation comments
- [x] My changes generate no new warnings

### CODE REVIEW

File: Sources/Client/Views/Play/WithRenderCoordinator.swift [hunk 1]
```diff
@@ -7,24 +7,40 @@ import DeltaRenderer
...
+        }
       }
     }
     .onAppear {
-      renderCoordinator = RenderCoordinator(client)
+      do {
+        try renderCoordinator = RenderCoordinator(client)
+      } catch let error as RendererError {
+        renderCoordinatorError = error
+      } catch {
```
Comment (ninjadev64) [inline Sources/Client/Views/Play/WithRenderCoordinator.swift:42]: this probably needs changing, or at the bare minimum needs a comment to explain that RendererError is the only error that can be thrown from the RenderCoordinator constructor

File: Sources/Core/Renderer/RenderCoordinator.swift [hunk 2]
```diff
@@ -3,6 +3,48 @@ import FirebladeMath
...
+  public private(set) var error: Error? = nil
+  
+  public var errorDescription: String? {
+    switch kind {
+      case .getMetalDevice:
+        return "Failed to get metal device"
+      case .makeRenderCommandQueue:
+        return "Failed to make render command queue"
+      case.camera:
+        return "Failed to create camera: \(String(describing: error!)) - \(error!.localizedDescription)"
```
Comment (ninjadev64) [inline Sources/Core/Renderer/RenderCoordinator.swift:28]: this is for stackotter's discretion but generally i've been told before to avoid force unwrapping in my contributions

File: Sources/Client/Views/Play/GameView.swift [hunk 3]
```diff
@@ -44,70 +44,74 @@ struct GameView: View {
...
-                  } else {
-                    InputView(listening: $inputCaptured, cursorCaptured: !inGameMenuPresented && cursorCaptured) {
-                      gameView(client: client, renderCoordinator: renderCoordinator)
-                    }
-                    .onKeyPress { [weak client] key, characters in
-                      client?.press(key, characters)
-                    }
-                    .onKeyRelease { [weak client] key in
-                      client?.release(key)
+        if let renderCoord = renderCoordinator {
```
Comment (ninjadev64) [inline Sources/Client/Views/Play/GameView.swift:47]: minor, but you could probably reuse the renderCoordinator identifier here

Comment (notdap) [reply Sources/Client/Views/Play/GameView.swift]: done!

File: Sources/Core/Renderer/RenderCoordinator.swift (hunk 2 above)
Comment (notdap) [reply Sources/Core/Renderer/RenderCoordinator.swift:28]: i'll let stackotter decide on this one. it should be safe to force unwrap here as in those cases an error is always passed

File: Sources/Client/Views/Play/WithRenderCoordinator.swift (hunk 1 above)
Comment (notdap) [reply Sources/Client/Views/Play/WithRenderCoordinator.swift:40]: should be a little clearer now ([0d615fd](https://github.com/stackotter/delta-client/pull/190/commits/0d615fd2dfd5f4b1daac611d0db1b07cf8b04026))
let me know what you think

File: Sources/Core/Renderer/RenderCoordinator.swift (hunk 2 above)
Comment (obvgab) [reply Sources/Core/Renderer/RenderCoordinator.swift:28]: You might also be able to get around this (and the empty `catch {}`) with enum associated values. I’ll suggest a change and let me know if it works.

Comment (obvgab) [reply Sources/Core/Renderer/RenderCoordinator.swift:28]: I made a PR on your repo. If you like the format feel free to use it. If you’d like to stay with Optionals for simplicity, that works too.

Comment (notdap) [reply Sources/Core/Renderer/RenderCoordinator.swift]: This has been improved (and solved) thanks to @obvgab's commit

File: Sources/Client/Views/Play/WithRenderCoordinator.swift (hunk 1 above)
Comment (notdap) [reply Sources/Client/Views/Play/WithRenderCoordinator.swift:42]: also solved by @obvgab's commit 🎉

File: Sources/Client/Views/Play/WithRenderCoordinator.swift [hunk 4]
```diff
@@ -7,24 +7,41 @@ import DeltaRenderer
 struct WithRenderCoordinator<Content: View>: View {
   var client: Client
   var content: (RenderCoordinator) -> Content
+  var cancel: () -> Void
 
-  init(for client: Client, @ViewBuilder content: @escaping (RenderCoordinator) -> Content) {
+  init(for client: Client, @ViewBuilder content: @escaping (RenderCoordinator?) -> Content, cancellationHandler cancel: @escaping () -> Void) {
     self.client = client
     self.content = content
```
Comment (stackotter) [inline Sources/Client/Views/Play/WithRenderCoordinator.swift:14]: How does this compile? The parameter `content` is a function taking an optional render coordinator but the property `content` is a function taking a required render coordinator.

File: Sources/Client/Views/Play/WithRenderCoordinator.swift [hunk 5]
```diff
@@ -7,24 +7,41 @@ import DeltaRenderer
...
+            .frame(width: 150)
+        } else {
+          Text("Creating render coordinator")
+        }
       }
     }
     .onAppear {
-      renderCoordinator = RenderCoordinator(client)
+      do {
+        try renderCoordinator = RenderCoordinator(client)
```
Comment (stackotter) [inline Sources/Client/Views/Play/WithRenderCoordinator.swift:39]: I didn't even know this was valid, the more you know! 😅 generally in Swift you'd do `renderCoordinator = try RenderCoordinator(client)`

File: Sources/Core/Renderer/RenderCoordinator.swift [hunk 6]
```diff
@@ -3,6 +3,55 @@ import FirebladeMath
 import MetalKit
 import DeltaCore
 
+public struct RendererError: LocalizedError {
```
Comment (stackotter) [inline Sources/Core/Renderer/RenderCoordinator.swift:6]: I think it'd make sense to just make `RendererError` itself an `enum` since it just has a single enum property (i.e. move the cases of `ErrorKind` onto `RendererError` itself).

File: Sources/Core/Renderer/RenderCoordinator.swift [hunk 7]
```diff
@@ -53,19 +102,18 @@ public final class RenderCoordinator: NSObject, MTKViewDelegate {
 
   /// The longest a frame has taken to encode so far.
   private var longestFrame: Double = 0
-
+
```
Comment (stackotter) [inline Sources/Core/Renderer/RenderCoordinator.swift:105]: Just a minor thing, but I usually avoid trailing whitespace (my editor removes it but I get that not all editors do that)

File: Sources/Client/Views/Play/GameView.swift [hunk 8]
```diff
@@ -44,70 +44,74 @@ struct GameView: View {
...
-        VStack {
-          switch state {
-            case .playing:
-              ZStack {
-                WithController(controller, listening: $inputCaptured) {
-                  if controllerOnly {
-                    gameView(client: client, renderCoordinator: renderCoordinator)
-                  } else {
-                    InputView(listening: $inputCaptured, cursorCaptured: !inGameMenuPresented && cursorCaptured) {
+        if let renderCoordinator = renderCoordinator {
```
Comment (stackotter) [inline Sources/Client/Views/Play/GameView.swift:47]: `WithRenderCoordinator`'s content should just take a `RenderCoordinator` instead of a `RenderCoordinator?` (which I think was your intention, I'm assuming this is probably just leftover from an earlier attempt).

**Comment by mattg42** [comment]
Any reason why `RendererError` is a `struct` with a separate error kind `enum` property, instead of just being an `enum` itself?

**Review by stackotter — CHANGES_REQUESTED** [review]
Looking good so far! You'll be a Swifty in no time hahah, thanks @ninjadev64 and @obvgab for helping out while I was asleep 😴

Just a few requested changes which are mostly about simplifying things that that were artefacts of previous attempts.

**Comment by stackotter** [comment]
> Any reason why `RendererError` is a `struct` with a separate error kind `enum` property, instead of just being an `enum` itself?

Hahah didn't see this until after I submitted my review, you beat me to it

File: Sources/Core/Renderer/RenderCoordinator.swift (hunk 7 above)
Comment (obvgab) [reply Sources/Core/Renderer/RenderCoordinator.swift:105]: Whoops that might have been me on Xcode

File: Sources/Client/Views/Play/WithRenderCoordinator.swift (hunk 5 above)
Comment (notdap) [reply Sources/Client/Views/Play/WithRenderCoordinator.swift:39]: I actually had it like that originally, but at some point I moved the try to the beginning of the line and now I sincerely don't even remember why

File: Sources/Client/Views/Play/WithRenderCoordinator.swift (hunk 4 above)
Comment (notdap) [reply Sources/Client/Views/Play/WithRenderCoordinator.swift:14]: Good catch, I'm actually not sure why the compiler isn't complaining. Xcode for sure at least didn't even mention a  warning 😮

File: Sources/Core/Renderer/RenderCoordinator.swift (hunk 6 above)
Comment (notdap) [reply Sources/Core/Renderer/RenderCoordinator.swift:6]: originally I wanted it to be an enum, but prior to gabriel's commit there was an error property. I assume it's okay to make it into an enum now

File: Sources/Client/Views/Play/WithRenderCoordinator.swift (hunk 4 above)
Comment (notdap) [reply Sources/Client/Views/Play/WithRenderCoordinator.swift:14]: should be alright now

File: Sources/Client/Views/Play/WithRenderCoordinator.swift (hunk 5 above)
Comment (notdap) [reply Sources/Client/Views/Play/WithRenderCoordinator.swift]: moved it in the latest commit

File: Sources/Client/Views/Play/GameView.swift (hunk 8 above)
Comment (notdap) [reply Sources/Client/Views/Play/GameView.swift:47]: ah I actually just commited a thing where I made content's RenderCoordinator nullable, but you're right, when used inside content it's never nil, so I'll fix that real quick now

Comment (notdap) [reply Sources/Client/Views/Play/GameView.swift]: done 😄

File: Sources/Core/Renderer/RenderCoordinator.swift (hunk 6 above)
Comment (notdap) [reply Sources/Core/Renderer/RenderCoordinator.swift]: latest commit makes it just an enum, thanks for pointing it out

File: Sources/Core/Renderer/RenderCoordinator.swift (hunk 7 above)
Comment (notdap) [reply Sources/Core/Renderer/RenderCoordinator.swift]: it has been removed

**Review by stackotter — APPROVED** [review]
Awesome, looks much better, thanks! 🎉

**Comment by stackotter** [comment]
I'll wait for the workflows to complete.
