### PR TITLE
Index through chat messages and commands using the arrow keys.

### LINKED ISSUE #160: Implement remaining chat input handling
It's easiest to explain this with an example. If you click the up arrow while writing a chat message, the game crashes (because it tries to render an up arrow) whereas it should replace the current text with the previous message that the user sent.

The main tasks are:
- [x] Support up and down arrow keys (to reuse previous messages/commands)
- [ ] Support left and right arrow keys (to navigate message input)
- [ ] Support using the shift key to highlight text along with the arrow keys
- [ ] Support cmd+x to cut the selection and cmd+c to copy the selection
- [ ] Support cmd+a to select all of the text
- [ ] Support backspacing selections
- [ ] Probably more that I haven't thought of yet

### PR DESCRIPTION
**Pull request by jxhug**
# Description

You can now index through chat messages and commands using the arrow keys. Fixes #160.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation comments
- [x] My changes generate no new warnings

### CODE REVIEW

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 1]
```diff
@@ -136,16 +136,60 @@ public final class PlayerInputSystem: System {
...
         }
+      } else if event.key == .upArrow {
+        // If no message is selected, select the above message
+        if guiState.currentMessageIndex == nil {
+          guiState.stashedMessageInput = guiState.messageInput
+          // If there are no messages, do nothing
+          if guiState.playerMessageHistory.count > 0 {
+            // Index up a message
+            guiState.currentMessageIndex = guiState.playerMessageHistory.count - 1
+            if let currentMessageIndex: Int = guiState.currentMessageIndex {
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:160]: The type annotation is unnecessary, and since it is simple it should be left out.

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 2]
```diff
@@ -136,16 +136,60 @@ public final class PlayerInputSystem: System {
...
+              // Set the message input to the message at the index
+              guiState.messageInput = guiState.playerMessageHistory[guiState.currentMessageIndex!]
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:162]: You don't need to force unwrap `guiState.currentMessageIndex`, you can replace it with `currentMessageIndex`. Alternatively (and probably better), you can actually just store `count - 1` in an `index` variable at line 159 and then assign `index` to `guiState.currentMessageIndex` afterwards. That way you don't have to do any unwrapping (you can completely avoid unwrapping in this case because you're setting the value immediately beforehand, and you know it's not `nil`, the trick is just knowing how to convince the compiler).

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 3]
```diff
@@ -136,16 +136,60 @@ public final class PlayerInputSystem: System {
...
+            }
+          }
+        } else {
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:165]: To avoid unwrapping, you should flip this if-else statement around like so:

```swift
if let index = guiState.currentMessageIndex, index > 0 {
  guiState.currentMessageIndex = index - 1
  guiState.messageInput = guiState.playerMessageHistory[index - 1]
} else if guiState.currentMessageIndex == nil {
  guiState.stashedMessageInput = guiState.messageInput
  if !guiState.playerMessageHistory.isEmpty {
    guiState.currentMessageIndex = guiState.playerMessageHistory.count - 1
    // ...
  }
}
```

Feel free to ask for help with that in the Discord if that's confusing

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 4]
```diff
@@ -136,16 +136,60 @@ public final class PlayerInputSystem: System {
...
+            guiState.currentMessageIndex! -= 1
+          }
+          if let currentMessageIndex: Int = guiState.currentMessageIndex {
+            // Set the message input to the message at the index
+            guiState.messageInput = guiState.playerMessageHistory[guiState.currentMessageIndex!]
+          }
+        }
+      } else if event.key == .downArrow {
+        // If there is a message selected, index down a message
+        if guiState.currentMessageIndex != nil {
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:177]: Avoid force unwrapping by converting the if statement to look like this:

```swift
if let index = guiState.currentMessageIndex {
```

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 5]
```diff
@@ -136,16 +136,60 @@ public final class PlayerInputSystem: System {
...
+          if guiState.currentMessageIndex! < guiState.playerMessageHistory.count - 1 {
+            guiState.currentMessageIndex! += 1
+            if let currentMessageIndex: Int = guiState.currentMessageIndex {
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:180]: `if let` is only useful if you use `currentMessageIndex` in the body of the if statement. In this case you don't and you force unwrap anyway. With the change I proposed for line 177 you can get rid of the if statement entirely, but it's just something to keep in mind.

**Review by stackotter — CHANGES_REQUESTED** [review]
The logic looks fine to me for the most part, I've just left a bunch of suggestions to help you fix up the code's handling of optionals. By the end of applying all the suggestions you should be able to get rid of all of the force unwraps! (and the code will be much simpler too). Feel free to ask about any of the suggestions in the Discord if they're confusing 👍

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 6]
```diff
@@ -136,16 +136,49 @@ public final class PlayerInputSystem: System {
...
+        if let index = guiState.currentMessageIndex, index > 0 {
+          guiState.currentMessageIndex = index - 1
+          guiState.messageInput = guiState.playerMessageHistory[index - 1]
+        } else if guiState.currentMessageIndex == nil {
+          guiState.stashedMessageInput = guiState.messageInput
+          if !guiState.playerMessageHistory.isEmpty {
+            guiState.currentMessageIndex = guiState.playerMessageHistory.count - 1
+            if let index = guiState.currentMessageIndex {
+              guiState.messageInput = guiState.playerMessageHistory[index]
+            }
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:163]: You can actually avoid the `if let` by replacing lines 160-163 with the following snippet. This is better because in your code the `if` actually makes it look like there's conditional logic when there's not (it will always execute).

```swift
let index = guistate.playerMessageHistory.count - 1
guiState.currentMessageIndex = index
guiState.messageInput = guiState.playerMessageHistory[index]
```

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 7]
```diff
@@ -136,16 +136,49 @@ public final class PlayerInputSystem: System {
...
           guiState.messageInput?.removeLast()
         }
+      } else if event.key == .upArrow {
+        // If no message is selected, select the above message
+        if let index = guiState.currentMessageIndex, index > 0 {
+          guiState.currentMessageIndex = index - 1
+          guiState.messageInput = guiState.playerMessageHistory[index - 1]
+        } else if guiState.currentMessageIndex == nil {
+          guiState.stashedMessageInput = guiState.messageInput
+          if !guiState.playerMessageHistory.isEmpty {
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:159]: If you swap lines 158 and 159 you can actually avoid having this nested if statement. You can put the `!isEmpty` check as an extra condition on line 157. This is possible because stashing the message input only needs to happen if the message actually gets replaced. Avoiding unnecessary double nesting (where it doesn't affect readability) is good because it simplifies the flow of code for someone reading the code (less paths to follow).

File: Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift [hunk 8]
```diff
@@ -136,16 +136,49 @@ public final class PlayerInputSystem: System {
...
+            guiState.currentMessageIndex = index + 1
+            guiState.messageInput = guiState.playerMessageHistory[index + 1]
+          } else {
+            // If there is no message to index down to, go back to what the user was typing originally
+            guiState.currentMessageIndex = nil
+            if let stashedMessage = guiState.stashedMessageInput {
+              guiState.messageInput = stashedMessage
+            } else {
+              guiState.messageInput = ""
+            }
```
Comment (stackotter) [inline Sources/Core/Sources/ECS/Systems/PlayerInputSystem.swift:179]: There's a very useful operator in Swift which you will find very handy here!

The following line of code is equivalent to that 5 line if-else block.

```swift
guiState.messageInput = guiState.stashedMessageInput ?? ""
```

The `??` operator will unwrap the optional on the left, or if the value is `nil` it will return `""` instead.

**Review by stackotter — CHANGES_REQUESTED** [review]
Just a few more suggestions to help you improve at handling optionals, I think you'll find the tip at line 175 very useful :)

**Review by stackotter — APPROVED** [review]
Looks great to me! I'll just quickly test it out before merging.

**Comment by stackotter** [comment]
It works 🎉
